// projectsData.ts
export const projects = [
  {
    name: 'portfolio',
    url: '/images/portfolio.jpg',
    title: 'My Portfolio',
    desc: "I was once told that a software engineer isn't a designer. While I agree, I didn't want to settle for a cookie cutter portfolio. I wanted to create something unique, clean, and personalized. This page is deployed using Github Pages.",
    badges: ['NextJS', 'React', 'Tailwind CSS', 'Github Pages'],
    github: 'https://github.com/wedward88/portfolio-v3',
    link: 'https://wedward.com',
  },
  {
    name: 'nyt-headliner',
    url: '/images/nyt-headliner.png',
    title: 'NYT Headliner',
    desc: 'Inspired by the New York Times Birthday Collection, this small app can be used to browse New York Times articles from a specified date. Deployed on a dedicated server running Apache2. ',
    badges: ['NextJS', 'React', 'Tailwind CSS', 'Apache2'],
    github: 'https://github.com/wedward88/nyt-headliner',
    link: 'https://nyt-headliner.wedward.com/',
  },
  {
    name: 'twodeeskate',
    url: '/images/twodeeskate.png',
    title: 'Two Dee Skate',
    desc: 'As an avid skateboarder, I had a blast creating this 2D side-scroller. Enjoy kickflipping over randomly generated obstacles, but avoid those gaps, and see how long you can survive!',
    badges: [
      'Javascript',
      'HTML5',
      'Canvas',
      'CSS3',
      'Webpack',
      'Github Pages',
    ],
    github: 'https://github.com/wedward88/TwoDeeSkate',
    link: 'https://wedward88.github.io/TwoDeeSkate/',
  },
  {
    name: 'endeavornote',
    url: '/images/endeavornote.png',
    title: 'Endeavornote',
    desc: 'A single page clone of Evernote with custom authentication. This was my very first full stack project back in 2019. Deployed on a dedicated server running Apache2.',
    badges: [
      'React',
      'Redux',
      'Ruby',
      'Rails',
      'PostgreSQL',
      'HTML5',
      'CSS3',
      'Apache2',
    ],
    github: 'https://github.com/wedward88/Endeavornote',
    link: 'https://endeavornote.wedward.com/#/',
  },
];
